server:
  port: 8001
spring:
  application:
    name: consumer-server  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos的服务注册中心地址
#开启熔断开关
feign:
  sentinel:
    enabled: true