server:
  port: 8201
spring:
  application:
    name: sleuth-a-server  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos的服务注册中心地址
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0  #spring.sleuth.sampler.probability=1.0表示以 100% 的概率将链路的数据上传给 Zipkin Server ， 在默认情况下 ， 该值为0.1
