server:
  port: 8100
spring:
  application:
    name: stream-sender  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos的服务注册中心地址
    stream:
      bindings: # 服务的整合处理
        msg-out: # 这个名字是一个通道的名称
          destination: myExchange # 表示要使用的Exchange名称定义
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: admin
    password: 123456